name: PlayertoSql
author: Vestri
description: Plugin Player to Sql
version: 0.9
main: main.java.PlayertoSql
depend: [ProtocolLib]
permissions:
  pts.ptsclear:
    description: clear folder
    default: op
commands:
  ptsclear:
    description: clear folder
    usage: /ptsclear