name: PlayertoSql
author: Vestri
description: Plugin Player to Sql
version: 0.28
api-version: 1.15
main: pts.java.PlayertoSql
depend: [ProtocolLib]
permissions:
  pts.ptsadmin:
    description: for all commands
    default: op
commands:
  ptsclear:
    description: clear folder
    usage: /ptsclear <player>
  ptsdiplsa:
    description: add player to disable on saves
    usage: /ptsdiplsa <player>
  ptsenplsa:
    description: remove player from disable on saves
    usage: /ptsenplsa <player>
  ptssaveplayer:
    description: save player if sync 1tick delay
    usage: /ptssaveplayer <player> [sync]
  ptsdipllo:
    description: add player to disable load on join
    usage: /ptsdipllo <player>
  ptsenpllo:
    description: remove player from load on join
    usage: /ptsenpllo <player>
  ptsloadplayer:
    description: load player if sync 1tick delay
    usage: /ptsloadplayer <player> [sync]
